name: Auth  CI/CD

on:
  push:
    paths:
      - 'demo-security/**'

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: echo "Welocme to Auth Service"

