eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
      defaultZone: http://localhost:8761/eureka/

  instance:
    #    hostname: eureka-0
    prefer-ip-address: true